### PR TITLE
Rails5 support

### PR DESCRIPTION
**Pull request by eitoball**

### CODE REVIEW

**Comment by estebanbouza** [comment]
@eitoball I have integrated your rails5 branch into my project. It all seems ok except for the `ActionCable` log events.
It seems when `ActionCable` logs an event, a variable holding `tags` is set to null when it shouldn't. I have narrowed it to this case, but I'm unsure how the fix should look like:

```
   55:     def tagged(*tags)
   56:         byebug if tags[0] == nil
=> 57:       @request = tags[0][0]
   58:       yield self
   59:     ensure
   60:       flush
   61:     end
(byebug) tags
[]
(byebug) where
--> #0  ActFluentLoggerRails::Logger.tagged(*tags#Array) at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/act-fluent-logger-rails-a304f7660eff/lib/act-fluent-logger-rails/logger.rb:57
    #1  ActionCable::Connection::TaggedLoggerProxy.tag(logger#ActFluentLoggerRails::FluentLogger) at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:22
    #2  ActionCable::Connection::TaggedLoggerProxy.log(type#Symbol, message#String) at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:36
    #3  block (2 levels) in ActionCable::Connection::TaggedLoggerProxy.block (2 levels) in <class:TaggedLoggerProxy>(message#String) at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:30
    #4  ActionCable::Connection::Base.process at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/connection/base.rb:71
    #5  ActionCable::Server::Base.call(env#Hash) at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actioncable-5.0.0/lib/action_cable/server/base.rb:28
    #6  block in block in <class:Constraints> at /Users/esteban/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/routing/mapper.rb:17
[... more]
```

Any hints on this?

**Comment by quek** [comment]
On Rails5 I got this error log.

```
Started GET "/" for 127.0.0.1 at 2016-07-09 11:22:17 +0900
Processing by RoomsController#show as HTML
  Rendering rooms/show.html.erb within layouts/application
  Rendered rooms/show.html.erb within layouts/application (0.3ms)
Completed 200 OK in 23ms (Views: 21.6ms | ActiveRecord: 0.0ms)


2016-07-09 11:22:17 +0900: Rack app error: #<NoMethodError: undefined method `delete' for nil:NilClass>
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_thread_safe_level.rb:23:in `local_level='
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:56:in `block (2 levels) in broadcast'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:22:in `ensure in silence'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:22:in `silence'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:20:in `silence'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/sprockets-rails-3.1.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/static.rb:136:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

https://github.com/rails/sprockets-rails/blob/master/lib/sprockets/rails/quiet_assets.rb#L11
`Rails.logger.silence { ... }`
This cause the error.

In rails console

```
yarn:~/job/actindi/work/rails5% bundle exec rails c
Running via Spring preloader in process 28564
Loading development environment (Rails 5.0.0)
>> Rails.logger.silence {}
NoMethodError: undefined method `delete' for nil:NilClass
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_thread_safe_level.rb:23:in `local_level='
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:56:in `block (2 levels) in broadcast'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:22:in `ensure in silence'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:22:in `silence'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger_silence.rb:20:in `silence'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
        from (irb):1
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
... 2 levels...
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
        from /home/ancient/job/actindi/work/rails5/vendor/bundler/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/ancient/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/ancient/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

I am under investigation.

Thanks,

**Comment by quek** [comment]
```
diff --git a/lib/act-fluent-logger-rails/logger.rb b/lib/act-fluent-logger-rails/logger.rb
index 76eedb8..a5670b8 100644
--- a/lib/act-fluent-logger-rails/logger.rb
+++ b/lib/act-fluent-logger-rails/logger.rb
@@ -74,6 +74,7 @@ module ActFluentLoggerRails
       @messages = []
       @log_tags = log_tags
       @map = {}
+      after_initialize if respond_to? :after_initialize
     end
 
     def add(severity, message = nil, progname = nil, &block)
```

This calls ActiveSupport::LoggerThreadSafeLevel#after_initialize.

**Comment by quek** [comment]
I create new pull request for the ActionCable issue.
@estebanbouza Could you try it?
https://github.com/actindi/act-fluent-logger-rails/pull/31

**Pull request merged**
